export const  FECTH_ALL_PRODUCTS = "FECTH_ALL_PRODUCTS" ; 
export const  FECTH_ALL_CART = "FECTH_ALL_CART" ; 
export const  CART_ADD_REMOVE_ACTION = "CART_ADD_REMOVE_ACTION"; 
export const  UPDATE_CART_ITEM = "UPDATE_CART_ITEM"
export const  CURRENT_RENDERING = "CURRENT_RENDERING"
export const SET_Y_OFFSET = 'SET_Y_OFFSET'